spark.authenticate true
spark.authenticate.secret spark-secret
spark.network.crypto.enabled true
spark.io.encryption.enabled true
spark.ssl.enabled true
spark.ssl.keyStore /opt/bitnami/spark/certs/spark-keystore.jks
spark.ssl.keyStorePassword changeit
spark.ssl.keyStoreType JKS
spark.ssl.trustStore /opt/bitnami/spark/certs/spark-truststore.jks
spark.ssl.trustStorePassword changeit
spark.ssl.trustStoreType JKS
spark.ssl.protocol TLSv1.2
